services:
    backend:
        build:
            context: .
            dockerfile: backend/Dockerfile
        container_name: nazrsabz-backend
        ports:
            - "${BACKEND_PORT}:3000"
        env_file:
            - .env
        volumes:
            - ./logs/backend:/app/logs # persistent logs
        restart: unless-stopped

    frontend:
        build:
            context: .
            dockerfile: frontend/Dockerfile
        container_name: nazrsabz-frontend
        ports:
            - "${FRONTEND_PORT}:80"
        env_file:
            - .env
        volumes:
            - ./logs/frontend:/usr/share/nginx/html/logs
        restart: unless-stopped
